### ISSUE TITLE
PIR compute unit syntax/convention questions

### ISSUE THREAD

**Issue by dkoeplin** [yaqiz01/pir#1]
I'm working on double checking the correctness of my PIR generation from Spatial now. I just had a couple of quick questions regarding the reduction syntax/conventions in PIR:

Looking at this part of the desugared version of DotProduct:

```
  val inner = {
    implicit val CU = ComputeUnit(name=Some("inner"), tpe=Pipe).updateParent(outer)
    // StateMachines / CounterChain
    val ii = CounterChain(tileSize by Const(1l)) //Local
    val itA = CounterChain.copy(tileLoadA, "it")
    val itB = CounterChain.copy(tileLoadB, "it")
    val s0::s1::s2::_ = Stages(3)
    // SRAMs
    val sA = SRAM(size=32, vec=tileLoadA.out, readAddr=ii(0), writeAddr=itA(0))
    val sB = SRAM(size=32, vec=tileLoadB.out, readAddr=ii(0), writeAddr=itB(0))
    //Scalar buffer
    val out = ScalarOut(output)
    // Pipeline Stages 
    Stage(s0, opds=List(sA.load,sB.load), o=FixMul, r=CU.reduce(s0))
    Stage.reduce(s1, op=FixAdd) 
    Stage(s2, opds=List(CU.reduce(s1)), o=Bypass, r=CU.scalarOut(s2, out))

    CU.updateFields(
      cchains=List(ii, itA, itB),
      srams=List(sA, sB),
      sins=Nil,
      souts=List(out),
      vins=List(VecIn(tileLoadA.out), VecIn(tileLoadB.out)),
      vouts=Nil
    )
  }
```
1. If I remember our earlier discussion, Stage.reduce expands into a tree corresponding to the number of lanes in the architecture. Does it create an accumulator as well? I don't see an explicit accumulator in the example code.
2. Is the assumption with Stage.reduce that the reduction function is composed of exactly one operation (i.e. only add, multiply, etc.)? 
3. Are the explicitly declared vector inputs from tileLoadA and tileLoadB declared here necessary? (We talked about this before but I forget what the final decision was)
4. Should this compute unit also copy its parent's counterchain? The parent's iterator isn't explicitly used, but if I'm thinking about it correctly you would want a copy for the control logic.

Thanks!

**Comment by yaqiz01** [comment]
1. Stage reduce doesn't include the accumulation stage. The example wasn't correct. I will update the example. Here we have the same issue of FPGA that we need to be able to set initial value of the accumulator. I will think about the syntax for that. 
2. That's the current assumption. I haven't really thought about a lambda as a reduction function. Probably the reduction will take a list of operations, where there's a partial map on some lanes followed by a reduce for each reduction stage in the tree. The example I'm thinking of is {_+3+_} on 4 parallel lanes, where the
- 1st stage is reduceReg+3 = reduceReg performed on lane 0 and lane 2
- 2nd stage reduce lane 0 and 1 to lane 0 with +, lane 2 and lane 3 to lane 2
- 3rd stage perform reduceReg + 3=reduceReg on lane 0
- 4th stage reduce lane 0 and 2 to lane 0 with +

So in theory I should be able to expand the tree with information represented in something like
Stage.reduce (sx, op=List(Add(3), Add))

This is a bit tricky. We can talk about what's the proper way of representing this

3 . Yeah the no sugar version was initially considered for in memory translation, where generating a lambda might be tricky. Since we are doing codegen, its' not any beneficial. Basically it's creating a CU with some mutable fields un-updated and then update at the end. So updateField(_,_,_,_) override all corresponding fields in the CU.

If you can change codegen slightly by keeping all CounterChain, SRAM, Pipeline codegen the same,
inside of doing

```
val inner = {
    implicit val CU = ComputeUnit(name=Some("inner"), tpe=Pipe).updateParent(outer)
    ...
    CU.updateFields( ...)
  }
```

Just do

```
val inner = ComputeUnit(name=Some("inner"), tpe=Pipe, parent=outer) { implicit CU =>
    ...
  }
```

Then you don't need to keep track of created counters, srams, ect. I will filter all nodes created inside the block and update the corresponding fields. 

4 . When a counter is copied that indicate a single bit wire in between the two CU to synchronize starting of the counter. If you remember our discussion with kunle and raghu the other day, copying counter chain in this case doesn't make control any cheaper since token also requires a single bit wire. The last stage of the outer controller does need outer counter chain for the control logic but that's done by merging the sequential/metapipeline CU in PIR into the last stage controller. Currently the assumption is the transformation happens in PIR, which I haven't really started. We can also do it in spatial, but I think it's slightly easier in PIR, not entirely sure. But we do miss the information more explicitly for which stage is the last one in a controller.

**Comment by yaqiz01** [comment]
I changed the reduction interface to no longer need explicit creating a stage and accum stage is also implicit because I can't mixin trait after they are created. 

So the interface look like

```
val acc:AccumStage = Stage.reduce(op=..., init=Const(...))
```

The result of the accumulation is in reduction register of acc, so to access

```
CU.reduce(acc)
```

Currently the assumption is still only one op for reduction. We can talk about how to handle an expression for more general case
I also updated the example. Sorry for changing back and forth on this
@dkoeplin 
To check your generation you can compile by putting the generated file in pir/app and either directly
`pir App` in pir/ or I recommend enter `sbt` repl first,  then `pir App`, which would be much faster for recompilation
