### ISSUE TITLE
PIR Syntax Questions

### ISSUE THREAD

**Issue by dkoeplin** [yaqiz01/pir#20]
PIR gen from Spatial is just about there, so I thought it'd be good to have a single place for remaining questions on PIR syntax.

1. Are multiple writers supported in PIR syntax or the architecture? I don't support this yet in scheduling/splitting, but we'll likely need it for at least LogReg. 

2. Should bypass operations count towards the total number of used stages? At the moment they do because I can't guarantee when a stage wouldn't be used.

**Comment by yaqiz01** [comment]
1. Multiple writer is not supported. We would need a mux in front of the write port and something that can connect to the select. What is the thing that providing the swap signal in FPGA?
   @raghup17 
   Are we planning on adding this?
2. Yeah seems conservatively they would count. Only eliminated when the bypassing from and to register are the same

**Comment by raghup17** [comment]
We can add some minimal support, as it seems to be a rather important feature. What kind of support is required? Looks like we need to be able to choose the write enable and write data signal based on something in the datapath. For the two cases:
1. LogReg: My understanding is that we have multiple writers here because a tile load, followed by an update. This requires choosing the write addr, write data and write en signal based on a counter value.
2. Groupbyreduce: We need to be able to use some bits in the input data address (key) to drive the write enable, but the write data is the same.

We can use the last few bits of the local write address register to act as write enable signals, along with muxes. I haven't thought this through completely though; want to make sure I understand the use cases. Are there other uses for multiple writers other than the ones above? Do we need to support writing to multiple buffers in an N-buffer?
